name: talio_travel
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  
  font_awesome_flutter: ^8.5.0
  firebase_database: ^3.0.7
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  shared_preferences: ^0.5.3+5
  cached_network_image: ^2.0.0-rc.1
  provider: ^3.1.0
  firebase_storage: ^3.0.6
  image_picker: ^0.6.1+4
  multi_image_picker: 4.6.4
  gallery_saver: ^1.0.7
  flutter_absolute_path: ^1.0.6
  google_maps_flutter: ^0.5.21+7
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  flare_flutter: ^1.6.2
  line_icons: ^0.2.0
  dots_indicator: ^1.0.0
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_masked_text: ^0.8.0
  sliding_up_panel: ^0.3.5
  toast: ^0.1.5
  intl: ^0.16.0
  http: ^0.12.0+2
  share: ^0.6.3
  camera: ^0.5.7+2
  lamp: 0.0.6
  rxdart: ^0.23.1
  video_player: ^0.10.8
  unicorndial: ^1.1.5
  path_provider: ^1.5.1
  native_device_orientation: ^0.3.0
  wakelock: ^0.1.3+3
  flutter_slidable: ^0.5.4
  image_cropper: ^1.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/search.png
    - assets/images/travel1.png
    - assets/images/travel2.png
    - assets/flr/success.flr
    - assets/flr/load.flr
    - assets/flr/splash.flr
    - assets/images/travel4.png
    - assets/images/travel5.png
    - assets/images/travel6.png
    - assets/images/empty.png
    - assets/images/restaurant.png
    - assets/images/hotel.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/talio_logo.jpg


  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
          
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600








  
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
